### ISSUE TITLE
Precedence over wildcards

### ISSUE THREAD

**Issue by jaytaph** [willdurand/Negotiation#54]
When given the following header:

    Accept: text/xml,text/*;q=0.6,application/pdf;q=0.6

it should prioritize `application/pdf` over `text/html`, as `application/pdf` is matched more specifically. This is taken from [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), chapter:

> If more than one media range applies to a given type, the most specific reference has precedence.

Right now, it prefers `text/html`.

**Comment by willdurand** [comment]
I don't think `application/pdf`is more specific than `text/xml` according to the sentence you pasted.

**Comment by jaytaph** [comment]
No, `text/xml` isnt...  but I said: `text/html`, which is

**Comment by willdurand** [comment]
In the priorities?

**Comment by neural-wetware** [comment]
In your example there is not more than one media range applying to a given type. So, the condition quoted from the RFC is not satisfied.

`text/*` applies to `test/html` and `application/pdf` applies to `application/pdf`. Only one media range applies to each of these server priorities.

Since they have the same `q` value, the choice comes down to server priority.

**Comment by jaytaph** [comment]
Ah that actually might make sense. Thanks!
